// app/shared/utils/Button.tsx
interface ButtonProps {
    label: string;
    type: 'submit' | 'button' | 'reset',
    pending: boolean
}

export function Button({label, type, pending}: ButtonProps) {

    return (
        <button type={type} disabled={pending}
                className="flex items-center justify-center px-5 py-2 leading-6 text-sm shadow rounded-md text-white font-bold bg-indigo-500 hover:bg-indigo-400 transition ease-in-out duration-150 disabled:cursor-not-allowed">
            {
                pending ? (
                    <>
                        <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg"
                             fill="none"
                             viewBox="0 0 24 24">
                            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor"
                                    strokeWidth="4"></circle>
                            <path className="opacity-75" fill="currentColor"
                                  d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                        </svg>
                        En cours de traitement...</>
                ) : label
            }
        </button>
    );
}

// src/app/shared/ui/button/button.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SpinnerComponent } from '../spinner/spinner.component';

@Component({
  selector: 'ui-button',
  standalone: true,
  imports: [CommonModule, SpinnerComponent],
  templateUrl: './button.component.html',
})
export class ButtonComponent {
  @Input() type: 'button' | 'submit' | 'reset' = 'submit';
  @Input() loading: boolean | null = false;
}

<button
  class="inline-flex w-full justify-center items-center px-4 py-2 font-semibold leading-6 text-sm shadow rounded-md text-white bg-indigo-500 hover:bg-indigo-400 transition ease-in-out duration-150 disabled:cursor-not-allowed"
  [disabled]="loading" [type]="type">
  @if (loading) {
    <ui-spinner/>
    En cours..
  } @else {
    <ng-content/>
  }
</button>
