// core/utils/Topbar.tsx
"use client";
import {useState} from "react";
import Link from "next/link";
import logo from "@/public/logo.png";
import Image from "next/image";
import {usePathname, useRouter} from "next/navigation";
import useStore from "@/core/hooks/useStore";
import {api} from "@/core/config/api";
import {User} from "@/core/_models";

type Link = {
    name: string;
    path: string;
    isShown: boolean;
};

const Topbar = () => {
    const [isOpen, setIsOpen] = useState<boolean>(false);
    const pathname: string = usePathname();
    const router = useRouter();
    const user: User | null = useStore.use.user();
    const setUser = useStore.use.setUser();

    const logOut = async (e: any) => {
        e.preventDefault();
        router.push("/");
        setUser(null);
        await api.post("auth/logout");
    };

    const trimName = (name: string) => {
        if (name.length > 15) {
            return name.substring(0, 15) + "...";
        }
        return name;
    };

    const LINKS: Link[] = [
        {
            name: "Accueil",
            path: "/",
            isShown: true,
        },
        {
            name: "Solutions",
            path: "/solutions",
            isShown: true,
        },
        {
            name: "Se connecter",
            path: "/login",
            isShown: user === null,
        },
        {
            name: "S'inscrire",
            path: "/register",
            isShown: user === null,
        },
        {
            name: trimName(user?.name || ""),
            path: "/profile",
            isShown: user !== null,
        },
    ];

    return (
        <header
            className={`fixed w-full text-gray-800 bg-white shadow-md px-10 py-4 z-10 flex items-center justify-between`}
        >
            <Link href={"/"} className={"inline-block"} aria-label="logo">
                <Image
                    src={logo}
                    alt={"Logo"}
                    className={"cursor-pointer w-24"}
                    priority={true}
                />
            </Link>
            <div className={`flex flex-col gap-2 lg:hidden ${isOpen && "active"}`} onClick={() => {
                setIsOpen(!isOpen);
            }}>
                <div className="h-[1px] w-6 bg-black transition-transform duration-300"></div>
                <div className="h-[1px] w-6 bg-black transition-transform duration-300"></div>
            </div>

            {/* Mobile navbar */}
            <div
                className={`absolute top-14 z-30 w-screen h-screen bg-white transition-transform shadow-xl duration-500 right-0 py-20 px-16 flex flex-col items-start gap-6 justify-start lg:hidden ${!isOpen && "-translate-y-[200%]"}`}>
                {LINKS.map(
                    (link, index) =>
                        link.isShown && (
                            <Link href={link.path} key={index}
                                  className={`transition-colors duration-300 flex items-center gap-1 ${pathname === link.path && "text-blue-800"}`}>
                                {link.name}
                            </Link>
                        )
                )}
                {user && <button onClick={logOut}>Déconnexion</button>}
            </div>

            {/* Desktop navbar */}
            <div className={"hidden lg:flex items-center gap-4"}>
                {LINKS.map(
                    (link, index) =>
                        link.isShown && (
                            <Link href={link.path} key={index}
                                  className={`transition-colors duration-300 flex items-center gap-1 ${pathname === link.path && "text-blue-800"}`}>
                                {link.name}
                            </Link>
                        )
                )}
                {user && <button onClick={logOut}>Déconnexion</button>}
            </div>
        </header>
    );
}

export default Topbar

// src/app/shared/ui/topbar/topbar.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule, NgOptimizedImage } from '@angular/common';
import { Router, RouterModule } from '@angular/router';
import { User } from '../../types/models-interfaces';
import { select, Store } from '@ngrx/store';
import { AppStoreInterface } from '../../types/app-store.interface';
import { userSelector } from '../../auth/store/auth.selectors';
import { Observable } from 'rxjs';

@Component({
  selector: 'ui-topbar',
  standalone: true,
  imports: [CommonModule, RouterModule, NgOptimizedImage],
  templateUrl: './topbar.component.html',
})
export class TopbarComponent {
  isOpen = signal(false);
  user$: Observable<User | null>;

  constructor(private store: Store<AppStoreInterface>, private router: Router) {
    this.user$ = this.store.pipe(select(userSelector));
  }

  links: { name: string; path: string; isShown: boolean }[] = [
    {
      name: 'Solutions',
      path: '/solutions',
      isShown: true,
    },
    {
      name: 'Se connecter',
      path: '/login',
      isShown: true,
    },
    {
      name: "S'inscrire",
      path: '/register',
      isShown: true,
    },
    {
      name: 'Profil',
      path: '/profile',
      isShown: false,
    },
  ];

  async logOut() {
    await this.router.navigate(['/']);
    // this.userService.setUser(null);
    // Assuming a logout API call
    // this.authService.logout().subscribe(() => {
    //   this.router.navigate(['/']);
    // });
  }

  trimName(name: string): string {
    if (name.length > 15) {
      return name.substring(0, 15) + '...';
    }
    return name;
  }

  toggleMenu(): void {
    this.isOpen.update((isOpen) => !isOpen);
  }
}

<header
  class="fixed w-full text-gray-800 bg-white shadow-md px-10 py-4 z-10 flex items-center justify-between"
>
  <a routerLink="/" class="inline-block" aria-label="logo">
    <img
      ngSrc="/assets/images/logo.webp"
      alt="Logo"
      class="cursor-pointer w-24"
      width="96"
      height="31"
      priority
    />
  </a>
  <div
    class="flex flex-col gap-2 lg:hidden"
    [ngClass]="{ active: isOpen() }"
    (click)="toggleMenu()"
  >
    <div class="h-[1px] w-6 bg-black transition-transform duration-300"></div>
    <div class="h-[1px] w-6 bg-black transition-transform duration-300"></div>
  </div>

  <!-- Mobile navbar -->
  <div
    class="absolute top-14 z-30 w-screen h-screen bg-white transition-transform shadow-xl duration-500 right-0 py-20 px-16 flex flex-col items-start gap-6 justify-start lg:hidden"
    [ngClass]="{ '-translate-y-[200%]': !isOpen() }"
  >
    @for (link of links; track link.path) { @if (link.isShown) {
    <a
      href=""
      [routerLink]="link.path"
      class="transition-colors duration-300"
      routerLinkActive="text-blue-800"
    >
      {{ link.name }}
    </a>
    } } @if (user$ | async) {
    <button (click)="logOut()">Déconnexion</button>
    }
  </div>

  <!-- Desktop navbar -->
  <div class="hidden lg:flex items-center gap-4">
    @for (link of links; track link.path) { @if (link.isShown && !(user$ |
    async)) {
    <a
      href=""
      [routerLink]="link.path"
      class="transition-colors duration-300"
      routerLinkActive="text-blue-800"
    >
      {{ link.name }}
    </a>
    } } @if (user$ | async) {
    <button (click)="logOut()">Déconnexion</button>
    }
  </div>
</header>
