// app/(pages)/solutions/page.tsx
import { Footer } from "@/app/shared/utils/Footer";
import Topbar from "@/app/shared/utils/Topbar";
import { SolutionCard } from "@/app/(pages)/solutions/components/SolutionCard";
import { Solution } from "@/app/shared/models/Solution";
import { Skeleton } from "@/app/shared/utils/ui/skeleton";
import { getMany } from "@/app/shared/_requests";

export default async function Solutions() {
  const solutions: Solution[] = [];

  return (
    <div className={"relative"}>
      <Topbar />
      <div
        className={
          "p-8 pt-28 text-gray-600 border-x border-dashed lg:mx-auto lg:max-w-screen-lg"
        }
      >
        <h3 className={"text-2xl font-bold mb-5"}>
          Les solutions innovantes de la communauté{" "}
          <span className={"text-indigo-700"}>({solutions.length})</span>
        </h3>
        <p className={"mb-10"}>
          Les solutions innovantes de la communauté sont des projets qui ont été
          mis en place par des organisations locales ou des individus pour
          résoudre les problèmes de la communauté.
        </p>
        <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
          {!solutions &&
            Array.from({ length: 10 }, (_, i) => (
              <Skeleton key={i} className={"animate-pulse h-[250px]"} />
            ))}
          {solutions &&
            solutions.map((solution: Solution, index: number) => (
              <SolutionCard key={index} solution={solution} />
            ))}
        </div>
      </div>
      <Footer />
    </div>
  );
}

// src/app/mapped-solutions/solutions/solutions.component.ts
import { Component } from '@angular/core';
import { Solution } from '../../shared/types/models-interfaces';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { SolutionCardComponent } from '../../shared/ui/solution-card/solution-card.component';
import { TopbarComponent } from '../../shared/ui/topbar/topbar.component';
import { FooterComponent } from '../../shared/ui/footer/footer.component';
import { Observable } from 'rxjs';
import { Store, select } from '@ngrx/store';
import { AppStoreInterface } from '../../shared/types/app-store.interface';
import * as solutionsActions from './store/solutions.actions';
import {
  cursorSelector,
  isLoadingSelector,
  solutionsSelector,
} from './store/solutions.selectors';
import { SpinnerComponent } from '../../shared/ui/spinner/spinner.component';
import {SolutionCardSkeletonComponent} from "../../shared/ui/solution-card-skeleton/solution-card-skeleton.component";

@Component({
  selector: 'fk-solutions',
  standalone: true,
  templateUrl: './solutions.component.html',
  imports: [
    CommonModule,
    RouterModule,
    SolutionCardComponent,
    TopbarComponent,
    FooterComponent,
    SpinnerComponent,
    SolutionCardSkeletonComponent,
  ],
})
export class SolutionsComponent {
  solutions$: Observable<Solution[]>;
  isLoading$: Observable<boolean>;
  cursor$: Observable<number>;
  cursor: number = 1;

  constructor(private store: Store<AppStoreInterface>) {
    this.store.dispatch(solutionsActions.load());
    this.solutions$ = this.store.pipe(select(solutionsSelector));
    this.isLoading$ = this.store.pipe(select(isLoadingSelector));
    this.cursor$ = this.store.pipe(select(cursorSelector));
  }

  loadMore() {
    this.store.dispatch(solutionsActions.loadMore());
  }
}

<div class="relative">
  <ui-topbar/>
  <div class="p-8 pt-28 text-gray-600 border-x border-dashed lg:mx-auto lg:max-w-screen-lg">
    <h3 class="text-2xl font-bold mb-5">
      Les solutions innovantes de la communauté
    </h3>
    <p class="mb-10">
      Les solutions innovantes de la communauté sont des projets qui ont été mis
      en place par des organisations locales ou des individus pour résoudre les
      problèmes de la communauté.
    </p>
    <div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
      @for (solution of solutions$ | async; track solution.id) {
        <ui-solution-card [solution]="solution"/>
      }
      @if (isLoading$ | async) {
        @for (i of [1, 2, 3, 4, 5, 6]; track i) {
          <ui-solution-card-skeleton/>
        }
      }
    </div>
    <div class="flex mt-8 w-full justify-center items-center text-sm">
      <hr class="w-full border-gray-300"/>
      <button type="button" [disabled]="isLoading$ | async"
              class="bg-none border w-1/2 rounded-full py-2 px-8 text-gray-950 hover:bg-gray-300/40 duration-75 disabled:opacity-50 disabled:pointer-events-none disabled:cursor-not-allowed"
              (click)="loadMore()">
        @if (isLoading$ | async) {
          <ui-spinner/>
        } @else {
          Voir plus
        }
      </button>
      <hr class="w-full border-gray-300"/>
    </div>
  </div>
  <ui-footer/>
</div>
