// src/app/shared/ui/input/input.component.ts
import { Component, inject, Input } from '@angular/core';
import { ControlContainer, ReactiveFormsModule } from '@angular/forms';
import { ApiValiationsErrorsInterface } from '../../auth/types/api-valiations-errors.interface';
import { NgClass } from '@angular/common';

@Component({
  selector: 'app-input',
  standalone: true,
  viewProviders: [
    {
      provide: ControlContainer,
      useFactory: () => inject(ControlContainer, { skipSelf: true })
    }
  ],
  imports: [ReactiveFormsModule, NgClass],
  templateUrl: './input.component.html'
})
export class InputComponent {
  @Input() name: string = '';
  @Input() label: string = '';
  @Input() type: 'email' | 'password' | 'text' | 'number' = 'text';
  @Input() placeholder: string = '';
  @Input() validationErrors: ApiValiationsErrorsInterface[] = [];

  getError(field: string): string {
    const error = this.validationErrors.find((error: ApiValiationsErrorsInterface) => error.property === field);
    if (!error) return '';
    return error.message;
  }
}

<div class="flex flex-col gap-4 transition-transform duration-300 ease-in">
  <label
    [htmlFor]="name"
    class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
    {{ label }}
  </label>
  <input
    [type]="type"
    [id]="name"
    autocomplete="off"
    class="h-9 w-full rounded-md border border-input bg-background px-3 py-5 text-sm transition-colors file:border-0 focus:outline-none focus:ring-1 ring-green-300"
    [placeholder]="placeholder"
    [name]="name"
    [formControlName]="name" />
  @if (getError(name)) {
  <p class="text-sm text-red-500">{{ getError(name) }}</p>
  }
</div>

// app/shared/utils/Input.tsx
interface InputProps {
    name: string;
    label: string;
    placeholder: string;
    error: string;
    type: string;
    value?: string;
}

export function Input({name, label, placeholder, error, value, type}: InputProps) {
    return (
        <div className="space-y-2">
            <label htmlFor={name} className="text-gray-800">
                {label}
            </label>
            <input
                id={name}
                type={type}
                name={name}
                defaultValue={value}
                autoComplete={name}
                placeholder={placeholder}
                className={`focus:outline-none text-sm block w-full placeholder:text-sm rounded-md border border-gray-200 px-4 py-3  placeholder:text-gray-600 transition-transform duration-300 ring-inset lg:text-base ${error ? 'ring-2 ring-red-500' : 'focus:ring-2 focus:ring-indigo-500'}`}
            />
            <p className={`text-red-700 text-sm mt-1 h-4 font-medium`}>
                {error}
            </p>
        </div>
    )
}
