// src/app/register/register.component.ts
import {Component, inject, OnInit} from '@angular/core';
import {NgOptimizedImage} from '@angular/common';
import {RouterLink} from '@angular/router';
import {FormBuilder, FormGroup, FormsModule, ReactiveFormsModule} from '@angular/forms';
import {FormCardComponent} from '../shared/ui/form-card/form-card.component';
import {FooterComponent} from '../shared/ui/footer/footer.component';
import {TopbarComponent} from '../shared/ui/topbar/topbar.component';
import {ButtonComponent} from '../shared/ui/button/button.component';
import {ButtonOutlineComponent} from '../shared/ui/button-outline/button-outline.component';
import {InputComponent} from '../shared/ui/input/input.component';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [
    FormCardComponent,
    FooterComponent,
    TopbarComponent,
    ButtonComponent,
    ButtonOutlineComponent,
    InputComponent,
    NgOptimizedImage,
    RouterLink,
    FormsModule,
    ReactiveFormsModule,
  ],
  templateUrl: './register.component.html',
})
export class RegisterComponent implements OnInit {
  form!: FormGroup;
  formBuilder = inject(FormBuilder);

  ngOnInit() {
    this.form = this.formBuilder.nonNullable.group({
      name: [''],
      email: [''],
      phoneNumber: [''],
      passwordConfirm: [''],
      password: [''],
    });
  }

  onSubmit() {
    if (this.form.invalid) {
      return console.log('Form is invalid');
    }
    console.log(this.form.value);
  }
}

<component-form-card formTitle="Inscrivez-vous" *ngIf="state$ | async as state" [error]="state.error || ''">
  <form [formGroup]="form" (ngSubmit)="onSubmit()" class="gap-8 flex flex-col justify-center">
    <ui-input type="text" name="name" label="Nom complet" placeholder="Entrez votre nom"
              [error]="getError(state.validationErrors, 'name')"/>
    <ui-input type="email" name="email" label="Email" placeholder="Entrez votre email"
              [error]="getError(state.validationErrors, 'email')"/>
    <ui-input type="text" name="phoneNumber" label="Numéro téléphonique" placeholder="Entrez votre numéro"
              [error]="getError(state.validationErrors, 'phoneNumber')"/>
    <ui-input type="text" name="address" label="Votre adresse" placeholder="Entrez votre adresse"
              [error]="getError(state.validationErrors, 'address')"/>
    <ui-input type="password" name="password" label="Mot de passe" placeholder="Entrez votre mot de passe"
              [error]="getError(state.validationErrors, 'password')"/>
    <ui-input type="password" name="passwordConfirm" label="Confirmez votre mot de passe"
              placeholder="Entrez votre confirmation" [error]="getError(state.validationErrors, 'passwordConfirm')"/>
    <ui-button type="submit" [loading]="state.isLoading" [disabled]="form.status === 'INVALID'">
      S'inscrire
    </ui-button>
    <hr class="my-6 border-gray-300 w-full"/>
    <ui-button-outline>
      <img ngSrc="assets/images/google.svg" alt="googlr" class="mr-2 h-4 w-4" width="10" height="10"/>
      <span class="text-gray-950 text-sm"> S'inscrire avec Google</span>
    </ui-button-outline>
    <a routerLink="/register" class="text-gray-950 text-sm">
      Pas encore de compte ? Inscrivez-vous
    </a>
  </form>
</component-form-card>

// app/(pages)/register/page.tsx
"use client";

import {toast, Toaster} from "react-hot-toast";
import Link from "next/link";
import {FormCard} from "@/app/shared/utils/formCard";
import Topbar from "@/app/shared/utils/Topbar";
import {getInputError} from "@/app/shared/helpers/getInputError";
import {Input} from "@/app/shared/utils/ui/input";
import {Label} from "@/app/shared/utils/ui/label";
import {Button} from "@/app/shared/utils/ui/button";
import {Loader2} from "lucide-react";
import Image from "next/image";
import googleLogo from "@/public/googleLogo.svg";
import {register} from "@/app/(pages)/register/_requests";
import {useMutate} from "@/app/shared/hooks/useMutate";
import {googleAuth} from "@/app/(pages)/_requests";
import {useRouter} from "next/navigation";
import {FormEvent} from "react";

export default function Register() {
    const router = useRouter()

    const getFormData = function (e: FormEvent) {
        const formData = new FormData(e.target as HTMLFormElement)
        return Object.fromEntries(formData)
    }

    const onSuccess = function () {
        toast.success('Inscription réussie')
        router.push('/login')
    }

    const {isLoading, mutate, errors} = useMutate(getFormData, register, onSuccess)

    return (
        <div className={'relative'}>
            <Topbar/>
            <FormCard title={"Inscrivez-vous"} handleSubmit={mutate}>
                <Label htmlFor={'name'}>Nom</Label>
                <Input name={'name'} placeholder={'Entrez le nom'} error={getInputError(errors, 'name')} type={'text'}/>

                <Label htmlFor={'email'}>Email</Label>
                <Input name={'email'} placeholder={'Entrez votre Email'} error={getInputError(errors, 'email')}
                       type={'email'}/>

                <Label htmlFor={'phoneNumber'}>Téléphone</Label>
                <Input name={'phoneNumber'} placeholder={'Entrez votre numéro Téléphone'}
                       error={getInputError(errors, 'phoneNumber')} type={'text'}/>

                <Label htmlFor={'address'}>Adresse</Label>
                <Input name={'address'} placeholder={'Entrez votre adresse'} error={getInputError(errors, 'address')}
                       type={'text'}/>

                <Label htmlFor={'password'}>Mot de passe</Label>
                <Input name={'password'} placeholder={'Entrez le mot de passe'}
                       error={getInputError(errors, 'password')} type={'password'}/>

                <Button type={'submit'} disabled={isLoading} className={'mt-5'}>
                    {
                        isLoading ? (
                            <>
                                <Loader2 className="mr-2 h-4 w-4 animate-spin"/>
                                En cours ...
                            </>
                        ) : "S'inscrire"
                    }
                </Button>
                <hr className="my-6 border-gray-300 w-full"/>
                <Button onClick={googleAuth} variant={'outline'} type={"button"}>
                    <Image src={googleLogo} alt={'img logo'} className="mr-2 h-4 w-4"/> S&apos;inscrire avec google
                </Button>
                <Link href={'/login'} className={"text-gray-950 text-sm"}>
                    Vous avez un compte ? Connectez-vous
                </Link>
            </FormCard>
            <Toaster/>
        </div>
    )
}
