// src/app/home/ui/about/about.component.ts
import { Component } from '@angular/core';
import {NgOptimizedImage} from "@angular/common";

@Component({
  selector: 'ui-about',
  standalone: true,
  imports: [
    NgOptimizedImage
  ],
  templateUrl: './about.component.html',
})
export class AboutComponent {
  partainers = [
    {
      id: 1,
      name: "ingenious city",
      src: "/assets/images/partainers/1.png",
    },
    {
      id: 2,
      name: "Un jour nouveau",
      src: "/assets/images/partainers/2.png",
    },
    {
      id: 3,
      name: "waza",
      src: "/assets/images/partainers/3.png",
    },
    {
      id: 4,
      name: "ukamili",
      src: "/assets/images/partainers/4.png",
    },
    {
      id: 5,
      name: "kadea",
      src: "/assets/images/partainers/5.png",
    },
    {
      id: 6,
      name: "ikiotahub",
      src: "/assets/images/partainers/6.png",
    },
    {
      id: 7,
      name: "work space",
      src: "/assets/images/partainers/7.png",
    },
    {
      id: 8,
      name: "kivuTech",
      src: "/assets/images/partainers/8.png",
    },
    {
      id: 9,
      name: "akili",
      src: "/assets/images/partainers/9.png",
    },
    {
      id: 10,
      name: "innovation hub",
      src: "/assets/images/partainers/10.png",
    },
    {
      id: 11,
      name: "habariRDC",
      src: "/assets/images/partainers/11.png",
    },
    {
      id: 12,
      name: "creationHub",
      src: "/assets/images/partainers/12.png",
    },
    {
      id: 13,
      name: "sadek",
      src: "/assets/images/partainers/13.png",
    },
    {
      id: 14,
      name: "base",
      src: "/assets/images/partainers/14.png",
    },
    {
      id: 15,
      name: "luba hub",
      src: "/assets/images/partainers/15.png",
    },
    {
      id: 16,
      name: "yPardRDC",
      src: "/assets/images/partainers/16.png",
    },
  ];
}

<div class="p-8 bg-white" id="about">
  <div class="lg:mx-auto border-t overflow-hidden lg:max-w-screen-lg py-20">
    <div class="grid grid-rows-1 md:grid-cols-2 gap-8 items-center content-center">
      <div class="flex flex-col gap-4">
        <h1 class="text-xl font-semibold">Qui sommes-nous ?</h1>
        <p>
          Fikiri est une plateforme web qui vise à cartographier les
          solutions locales en République Démocratique du Congo pour
          accélérer l&apos;atteinte des Objectifs de Développement Durable
          (ODD). L&apos;objectif de Fikiri est de mettre en lumière les
          solutions locales qui contribuent à l&apos;atteinte des ODD en
          RDC. Cela permettra de faciliter la recherche des solutions
          locales par les organisations internationales et les bailleurs de
          fonds.
        </p>
      </div>
      <img ngSrc='/assets/images/about.jpeg' alt="About image" class="rounded-md" width="1600" height="900"/>
    </div>
    <div class="flex gap-2 flex-wrap">
      @for (partainer of partainers; track partainer.id) {
        <img [ngSrc]="partainer.src" [alt]="partainer.name" class="w-32" width="360" height="270">
      }
    </div>
  </div>
</div>

// app/components/About.tsx
import ingeniousCity from "@/public/partainers/1.png";
import unJourNouveau from "@/public/partainers/2.png";
import waza from "@/public/partainers/3.png";
import ukamili from "@/public/partainers/4.png";
import kadea from "@/public/partainers/5.png";
import ikiotahub from "@/public/partainers/6.png";
import workSpace from "@/public/partainers/7.png";
import kivuTech from "@/public/partainers/8.png";
import akili from "@/public/partainers/9.png";
import innovationHub from "@/public/partainers/10.png";
import habariRDC from "@/public/partainers/11.png";
import creationHub from "@/public/partainers/12.png";
import sadek from "@/public/partainers/13.png";
import base from "@/public/partainers/14.png";
import luBaHub from "@/public/partainers/15.png";
import yPardRDC from "@/public/partainers/16.png";
import about from "@/public/about.jpeg";
import Image from "next/image";

const PARTAINERS = [
    {
        id: 1,
        nom: "ingenious city",
        src: ingeniousCity,
    },
    {
        id: 2,
        nom: "Un jour nouveau",
        src: unJourNouveau,
    },
    {
        id: 3,
        nom: "waza",
        src: waza,
    },
    {
        id: 4,
        nom: "ukamili",
        src: ukamili,
    },
    {
        id: 5,
        nom: "kadea",
        src: kadea,
    },
    {
        id: 6,
        nom: "ikiotahub",
        src: ikiotahub,
    },
    {
        id: 7,
        nom: "work space",
        src: workSpace,
    },
    {
        id: 8,
        nom: "kivuTech",
        src: kivuTech,
    },
    {
        id: 9,
        nom: "akili",
        src: akili,
    },
    {
        id: 10,
        nom: "innovation hub",
        src: innovationHub,
    },
    {
        id: 11,
        nom: "habariRDC",
        src: habariRDC,
    },
    {
        id: 12,
        nom: "creationHub",
        src: creationHub,
    },
    {
        id: 13,
        nom: "sadek",
        src: sadek,
    },
    {
        id: 14,
        nom: "base",
        src: base,
    },
    {
        id: 15,
        nom: "luba hub",
        src: luBaHub,
    },
    {
        id: 16,
        nom: "yPardRDC",
        src: yPardRDC,
    },
];

export function About() {
    return (
        <div className={"p-8 bg-white"} id={"about"}>
            <div
                className={"lg:mx-auto border-t overflow-hidden lg:max-w-screen-lg py-20"}>
                <div className="grid grid-rows-1 md:grid-cols-2 gap-8 items-center content-center">
                    <div className={"flex flex-col gap-4"}>
                        <h1 className={'text-xl font-semibold'}>Qui sommes-nous ?</h1>
                        <p>
                              Fikiri est une plateforme web qui vise à cartographier les solutions
                              locales en République Démocratique du Congo pour accélérer
                              l&apos;atteinte des Objectifs de Développement Durable (ODD).
                              L&apos;objectif de Fikiri est de mettre en lumière les solutions
                              locales qui contribuent à l&apos;atteinte des ODD en RDC. Cela
                              permettra de faciliter la recherche des solutions locales par les
                              organisations internationales et les bailleurs de fonds.
                        </p>
                    </div>
                    <Image
                        src={about}
                        alt={"About"}
                        className={"rounded-lg"}
                    />
                </div>

                <div
                    className="w-full inline-flex flex-nowrap overflow-hidden [mask-image:_linear-gradient(to_right,transparent_0,_black_128px,_black_calc(100%-200px),transparent_100%)]">
                    <ul className="flex items-center justify-center md:justify-start [&_li]:mx-8 [&_img]:max-w-none animate-infinite-scroll">
                        {PARTAINERS.map((partainer, index) => (
                            <li key={index}>
                                <Image
                                    src={partainer.src}
                                    alt={partainer.nom}
                                    className={"w-36"}
                                />
                            </li>
                        ))}
                    </ul>
                    <ul className="flex items-center justify-center md:justify-start [&_li]:mx-8 [&_img]:max-w-none animate-infinite-scroll" aria-hidden="true">
                        {PARTAINERS.map((partainer, index) => (
                            <li key={index}>
                                <Image
                                    src={partainer.src}
                                    alt={partainer.nom}
                                    className={"w-36"}
                                />
                            </li>
                        ))}
                    </ul>
                </div>
            </div>
        </div>
    );
}
