// src/app/home/components/about/about.component.ts
import { Component } from '@angular/core';
import { NgOptimizedImage } from '@angular/common';
import { YouTubePlayer } from '@angular/youtube-player';

@Component({
  selector: 'app-about',
  standalone: true,
  imports: [NgOptimizedImage, YouTubePlayer],
  templateUrl: './about.component.html',
})
export class AboutComponent {
  partainers = [
    {
      id: 1,
      name: 'ingenious city',
      src: '/assets/images/partainers/1.png',
    },
    {
      id: 2,
      name: 'Un jour nouveau',
      src: '/assets/images/partainers/2.png',
    },
    {
      id: 3,
      name: 'waza',
      src: '/assets/images/partainers/3.png',
    },
    {
      id: 4,
      name: 'ukamili',
      src: '/assets/images/partainers/4.png',
    },
    {
      id: 5,
      name: 'kadea',
      src: '/assets/images/partainers/5.png',
    },
    {
      id: 6,
      name: 'ikiotahub',
      src: '/assets/images/partainers/6.png',
    },
    {
      id: 7,
      name: 'work space',
      src: '/assets/images/partainers/7.png',
    },
    {
      id: 8,
      name: 'kivuTech',
      src: '/assets/images/partainers/8.png',
    },
    {
      id: 9,
      name: 'akili',
      src: '/assets/images/partainers/9.png',
    },
    {
      id: 10,
      name: 'innovation hub',
      src: '/assets/images/partainers/10.png',
    },
    {
      id: 11,
      name: 'habariRDC',
      src: '/assets/images/partainers/11.png',
    },
    {
      id: 12,
      name: 'creationHub',
      src: '/assets/images/partainers/12.png',
    },
    {
      id: 13,
      name: 'sadek',
      src: '/assets/images/partainers/13.png',
    },
    {
      id: 14,
      name: 'base',
      src: '/assets/images/partainers/14.png',
    },
    {
      id: 15,
      name: 'luba hub',
      src: '/assets/images/partainers/15.png',
    },
    {
      id: 16,
      name: 'yPardRDC',
      src: '/assets/images/partainers/16.png',
    },
  ];
}

<section
  class="p-8 lg:mx-auto lg:p-4 flex flex-col gap-4 justify-center w-full overflow-hidden lg:max-w-screen-lg mb-20">
  <h1 class="text-xl md:text-2xl lg:text-3xl font-semibold mb-6 mt-10">
    Fikiri, de quoi
    <span class="inline-block after:block after:w-full after:h-2 after:-mt-2 after:bg-green-300">s'agit-il</span> ?
  </h1>
  <div class="grid grid-cols-1 md:grid-cols-2 gap-x-8">
    <div class="flex flex-col justify-center items-start gap-6">
      <h2 class="text-xl md:text-3xl font-semibold md:w-2/3">Fikiri : Cartographie des solutions locales en RDC</h2>
      <p class="md:text-lg font-medium mb-3">
        Une plateforme dédiée à la cartographie, l'exploration et l'expérimentation des solutions innovantes locales
        pour accélérer l'atteinte des Objectifsde Développement durables . En savoir plus? Regardez la vidéo ci-dessous.
      </p>
    </div>
    <youtube-player videoId="xuCLFkqhZAs" width="fill" height="400" />
  </div>
  <div
    class="w-full inline-flex flex-nowrap overflow-hidden [mask-image:_linear-gradient(to_right,transparent_0,_black_128px,_black_calc(100%-200px),transparent_100%)]">
    <ul
      class="flex items-center justify-center md:justify-start [&_li]:mx-8 [&_img]:max-w-none animate-infinite-scroll">
      @for (partainer of partainers; track partainer.id) {
        <div class="h-32 w-32 relative object-contain">
          <img [ngSrc]="partainer.src" [alt]="partainer.name" class="partner-logo" fill />
        </div>
      }
    </ul>
    <ul
      class="flex items-center justify-center md:justify-start [&_li]:mx-8 [&_img]:max-w-none animate-infinite-scroll"
      aria-hidden="true">
      @for (partainer of partainers; track partainer.id) {
        <div class="h-32 w-32 relative object-contain">
          <img [ngSrc]="partainer.src" [alt]="partainer.name" class="partner-logo" fill />
        </div>
      }
    </ul>
  </div>
</section>

// app/components/About.tsx
import ingeniousCity from "@/public/partainers/1.png";
import unJourNouveau from "@/public/partainers/2.png";
import waza from "@/public/partainers/3.png";
import ukamili from "@/public/partainers/4.png";
import kadea from "@/public/partainers/5.png";
import ikiotahub from "@/public/partainers/6.png";
import workSpace from "@/public/partainers/7.png";
import kivuTech from "@/public/partainers/8.png";
import akili from "@/public/partainers/9.png";
import innovationHub from "@/public/partainers/10.png";
import habariRDC from "@/public/partainers/11.png";
import creationHub from "@/public/partainers/12.png";
import sadek from "@/public/partainers/13.png";
import base from "@/public/partainers/14.png";
import luBaHub from "@/public/partainers/15.png";
import yPardRDC from "@/public/partainers/16.png";
import about from "@/public/about.jpeg";
import Image from "next/image";

const PARTAINERS = [
    {
        id: 1,
        nom: "ingenious city",
        src: ingeniousCity,
    },
    {
        id: 2,
        nom: "Un jour nouveau",
        src: unJourNouveau,
    },
    {
        id: 3,
        nom: "waza",
        src: waza,
    },
    {
        id: 4,
        nom: "ukamili",
        src: ukamili,
    },
    {
        id: 5,
        nom: "kadea",
        src: kadea,
    },
    {
        id: 6,
        nom: "ikiotahub",
        src: ikiotahub,
    },
    {
        id: 7,
        nom: "work space",
        src: workSpace,
    },
    {
        id: 8,
        nom: "kivuTech",
        src: kivuTech,
    },
    {
        id: 9,
        nom: "akili",
        src: akili,
    },
    {
        id: 10,
        nom: "innovation hub",
        src: innovationHub,
    },
    {
        id: 11,
        nom: "habariRDC",
        src: habariRDC,
    },
    {
        id: 12,
        nom: "creationHub",
        src: creationHub,
    },
    {
        id: 13,
        nom: "sadek",
        src: sadek,
    },
    {
        id: 14,
        nom: "base",
        src: base,
    },
    {
        id: 15,
        nom: "luba hub",
        src: luBaHub,
    },
    {
        id: 16,
        nom: "yPardRDC",
        src: yPardRDC,
    },
];

export function About() {
    return (
        <div className={"p-8 bg-white"} id={"about"}>
            <div
                className={"lg:mx-auto border-t overflow-hidden lg:max-w-screen-lg py-20"}>
                <div className="grid grid-rows-1 md:grid-cols-2 gap-8 items-center content-center">
                    <div className={"flex flex-col gap-4"}>
                        <h1 className={'text-xl font-semibold'}>Qui sommes-nous ?</h1>
                        <p className={'font-medium text-base leading-8'}>
                              Fikiri est une plateforme web qui vise à cartographier les solutions
                              locales en République Démocratique du Congo pour accélérer
                              l&apos;atteinte des Objectifs de Développement Durable (ODD).
                              L&apos;objectif de Fikiri est de mettre en lumière les solutions
                              locales qui contribuent à l&apos;atteinte des ODD en RDC. Cela
                              permettra de faciliter la recherche des solutions locales par les
                              organisations internationales et les bailleurs de fonds.
                        </p>
                    </div>
                    <Image
                        src={about}
                        alt={"About"}
                        className={"rounded-lg"}
                    />
                </div>

                <div
                    className="w-full inline-flex flex-nowrap overflow-hidden [mask-image:_linear-gradient(to_right,transparent_0,_black_128px,_black_calc(100%-200px),transparent_100%)]">
                    <ul className="flex items-center justify-center md:justify-start [&_li]:mx-8 [&_img]:max-w-none animate-infinite-scroll">
                        {PARTAINERS.map((partainer, index) => (
                            <li key={index}>
                                <Image
                                    src={partainer.src}
                                    alt={partainer.nom}
                                    className={"ml-2 w-40"}
                                />
                            </li>
                        ))}
                    </ul>
                    <ul className="flex items-center justify-center md:justify-start [&_li]:mx-8 [&_img]:max-w-none animate-infinite-scroll"
                        aria-hidden="true">
                        {PARTAINERS.map((partainer, index) => (
                            <li key={index}>
                                <Image
                                    src={partainer.src}
                                    alt={partainer.nom}
                                    className={"ml-2 w-40"}
                                />
                            </li>
                        ))}
                    </ul>
                </div>
            </div>
        </div>
    );
}
