// src/app/home/components/sdg/sdg.component.ts
import {Component} from '@angular/core';
import {AsyncPipe, NgIf, NgOptimizedImage} from "@angular/common";
import {SdgInterface} from "./types/sdg.interface";

@Component({
  selector: 'app-sdg',
  standalone: true,
  imports: [NgOptimizedImage, AsyncPipe, NgIf],
  templateUrl: './sdg.component.html',
})
export class SdgComponent {
  sdgs: SdgInterface[] = [
    {
      name: "Pas de pauvreté",
      description: "Éliminer la pauvreté sous toutes ses formes et partout dans le monde.",
      image: "assets/images/goals/F-WEB-Goal-1.png",
      isOpen: false
    },
    {
      name: "Faim zéro",
      description: "Assurer la sécurité alimentaire, améliorer la nutrition et promouvoir l'agriculture durable.",
      image: "assets/images/goals/F-WEB-Goal-2.png",
      isOpen: false
    },
    {
      name: "Bonne santé et bien-être",
      description: "Garantir une vie saine et promouvoir le bien-être pour tous à tout âge.",
      image: "assets/images/goals/F-WEB-Goal-3.png",
      isOpen: false
    },
    {
      name: "Éducation de qualité",
      description: "Assurer une éducation inclusive, équitable et de qualité et promouvoir des possibilités d'apprentissage tout au long de la vie pour tous.",
      image: "assets/images/goals/F-WEB-Goal-4.png",
      isOpen: false
    },
    {
      name: "Égalité entre les sexes",
      description: "Parvenir à l'égalité des sexes et autonomiser toutes les femmes et les filles.",
      image: "assets/images/goals/F-WEB-Goal-5.png",
      isOpen: false
    },
    {
      name: "Eau propre et assainissement",
      description: "Garantir la disponibilité et la gestion durable de l'eau et de l'assainissement pour tous.",
      image: "assets/images/goals/F-WEB-Goal-6.png",
      isOpen: false
    },
    {
      name: "Énergie propre et d'un coût abordable",
      description: "Garantir l'accès de tous à des services énergétiques fiables, durables et modernes à un coût abordable.",
      image: "assets/images/goals/F-WEB-Goal-7.png",
      isOpen: false
    },
    {
      name: "Travail décent et croissance économique",
      description: "Promouvoir une croissance économique soutenue, inclusive et durable, le plein emploi productif et un travail décent pour tous.",
      image: "assets/images/goals/F-WEB-Goal-8.png",
      isOpen: false
    },
    {
      name: "Industrie, innovation et infrastructure",
      description: "Construire une infrastructure résiliente, promouvoir une industrialisation durable qui profite à tous et encourager l'innovation.",
      image: "assets/images/goals/F-WEB-Goal-9.png",
      isOpen: false
    },
    {
      name: "Réduction des inégalités",
      description: "Réduire les inégalités dans les pays et d'un pays à l'autre.",
      image: "assets/images/goals/F-WEB-Goal-10.png",
      isOpen: false
    },
    {
      name: "Villes et communautés durables",
      description: "Faire en sorte que les villes et les établissements humains soient ouverts à tous, sûrs, résilients et durables.",
      image: "assets/images/goals/F-WEB-Goal-11.png",
      isOpen: false
    },
    {
      name: "Consommation et production responsables",
      description: "Adopter des modes de consommation et de production durables.",
      image: "assets/images/goals/F-WEB-Goal-12.png",
      isOpen: false
    },
    {
      name: "Lutte contre les changements climatiques",
      description: "Prendre d'urgence des mesures pour lutter contre les changements climatiques et leurs répercussions.",
      image: "assets/images/goals/F-WEB-Goal-13.png",
      isOpen: false
    },
    {
      name: "Vie aquatique",
      description: "Préserver et exploiter de manière durable les océans, les mers et les ressources marines.",
      image: "assets/images/goals/F-WEB-Goal-14.png",
      isOpen: false
    },
    {
      name: "Vie terrestre",
      description: "Préserver et restaurer les écosystèmes terrestres, en veillant à les exploiter de manière durable.",
      image: "assets/images/goals/F-WEB-Goal-15.png",
      isOpen: false
    },
    {
      name: "Paix, justice et institutions efficaces",
      description: "Promouvoir des sociétés pacifiques et inclusives pour un développement durable, assurer l'accès à la justice pour tous et mettre en place des institutions efficaces, responsables et inclusives à tous les niveaux.",
      image: "assets/images/goals/F-WEB-Goal-16.png",
      isOpen: false
    },
    {
      name: "Partenariats pour la réalisation des objectifs",
      description: "Stimuler le partenariat mondial pour le développement durable.",
      image: "assets/images/goals/F-WEB-Goal-17.png",
      isOpen: false
    }
  ];
}

<section class="max-w-screen-lg mx-auto mt-10 p-8">
  <h1 class="text-xl md:text-2xl lg:text-3xl font-semibold mb-6">Les objectifs de développement <span
    class="inline-block after:block after:w-full after:h-2 after:-mt-2 after:bg-green-300">durables</span></h1>
  <div
    class="grid lg:grid-cols-5 sm:grid-cols-4 grid-cols-2 gap-x-4 gap-y-6 mt-4 pb-1">
    @for (sdg of sdgs; track sdg.name) {
      <article class="group">
        <div class="relative mb-3">
          <div class="relative h-32 w-32">
            <img [ngSrc]="sdg.image" class="h-32 w-32 group:transition"
                 alt="{{sdg.name}}" fill>
          </div>
        </div>
        <span class="block leading-5 text-sm text-gray-600">{{ sdg.description }}</span>
      </article>
    }
  </div>
</section>

// app/components/Sdg.tsx
import odd1 from "@/public/goals/F-WEB-Goal-01.png";
import odd2 from "@/public/goals/F-WEB-Goal-02.png";
import odd3 from "@/public/goals/F-WEB-Goal-03.png";
import odd4 from "@/public/goals/F-WEB-Goal-04.png";
import odd5 from "@/public/goals/F-WEB-Goal-05.png";
import odd6 from "@/public/goals/F-WEB-Goal-06.png";
import odd7 from "@/public/goals/F-WEB-Goal-07.png";
import odd8 from "@/public/goals/F-WEB-Goal-08.png";
import odd9 from "@/public/goals/F-WEB-Goal-09.png";
import odd10 from "@/public/goals/F-WEB-Goal-10.png";
import odd11 from "@/public/goals/F-WEB-Goal-11.png";
import odd12 from "@/public/goals/F-WEB-Goal-12.png";
import odd13 from "@/public/goals/F-WEB-Goal-13.png";
import odd14 from "@/public/goals/F-WEB-Goal-14.png";
import odd15 from "@/public/goals/F-WEB-Goal-15.png";
import odd16 from "@/public/goals/F-WEB-Goal-16.png";
import odd17 from "@/public/goals/F-WEB-Goal-17.png";
import Image from "next/image";

export default function Sdg() {
    const sdgs = [
        {
            oddImage: odd1,
            oddTitle:
                "Éliminer la pauvreté sous toutes ses formes et partout dans le monde",
            path: "red-500",
        },
        {
            oddImage: odd2,
            oddTitle:
                "Éliminer la faim, assurer la sécurité alimentaire, améliorer la nutrition et promouvoir l’agriculture durable",
            path: "orange-800",
        },
        {
            oddImage: odd3,
            oddTitle:
                "Permettre à tous de vivre en bonne santé et promouvoir le bien-être de tous à tout âge",
            path: "green-600",
        },
        {
            oddImage: odd4,
            oddTitle:
                "Assurer l’accès de tous à une éducation de qualité, sur un pied d’égalité, et promouvoir les possibilités d’apprentissage tout au long de la vie",
            path: "red-700",
        },
        {
            oddImage: odd5,
            oddTitle:
                "Parvenir à l’égalité des sexes et autonomiser toutes les femmes et les filles",
            path: "pink-500",
        },
        {
            oddImage: odd6,
            oddTitle:
                "Garantir l’accès de tous à des services d’alimentation en eau et d’assainissement gérés de façon durable",
            path: "blue-500",
        },
        {
            oddImage: odd7,
            oddTitle:
                "Garantir l’accès de tous à des services énergétiques fiables, durables et modernes, à un coût abordable",
            path: "yellow-500",
        },
        {
            oddImage: odd8,
            oddTitle:
                "Promouvoir une croissance économique soutenue, partagée et durable, le plein emploi productif et un travail décent pour tous",
            path: "red-500",
        },
        {
            oddImage: odd9,
            oddTitle:
                "Bâtir une infrastructure résiliente, promouvoir une industrialisation durable qui profite à tous et encourager l’innovation",
            path: "orange-400",
        },
        {
            oddImage: odd10,
            oddTitle: "Réduire les inégalités dans les pays et d’un pays à l’autre",
            path: "pink-500",
        },
        {
            oddImage: odd11,
            oddTitle:
                "Faire en sorte que les villes et les établissements humains soient ouverts à tous, sûrs, résilients et durables",
            path: "yellow-800",
        },
        {
            oddImage: odd12,
            oddTitle: "Établir des modes de consommation et de production durables",
            path: "orange-400",
        },
        {
            oddImage: odd13,
            oddTitle:
                "Prendre d’urgence des mesures pour lutter contre les changements climatiques et leurs répercussions",
            path: "green-600",
        },
        {
            oddImage: odd14,
            oddTitle:
                "Conserver et exploiter de manière durable les océans, les mers et les ressources marines aux fins du développement durable",
            path: "blue-500",
        },
        {
            oddImage: odd15,
            oddTitle:
                "Préserver et restaurer les écosystèmes terrestres, en veillant à les exploiter de façon durable,...",
            path: "bg-cyan-800",
        },
        {
            oddImage: odd16,
            oddTitle:
                "Promouvoir des sociétés pacifiques et inclusives pour le développement durable, permettre un accès à la justice pour tous...",
            path: "bg-cyan-800",
        },
        {
            oddImage: odd17,
            oddTitle:
                "Renforcer les moyens de mettre en œuvre le Partenariat mondial pour le développement et le revitaliser.",
            path: "bg-cyan-800",
        },
    ];

    return (
        <div className={"p-8 mx-auto max-w-screen-lg"}>
            <h2 className={"font-bold text-xl mb-8"}>
                Les objectifs de développement durables (ODD)
            </h2>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
                {sdgs.map((sdg, index) => (
                    <div
                        className={`flex flex-col gap-4 justify-start items-start transition-colors duration-500 border rounded-lg p-6 hover:border-gray-300`}
                        key={index}>
                        <div className={"w-24 h-24 relative overflow-hidden"}>
                            <Image
                                src={sdg.oddImage}
                                alt={sdg.oddTitle}
                                className={"rounded-md object-cover"}
                            />
                        </div>
                        <span className={"font-medium inline-block"}>
              {sdg.oddTitle}
            </span>
                    </div>
                ))}
            </div>
        </div>
    );
}
