// app/shared/utils/formCard.tsx
import {FormEvent, ReactNode} from "react";

interface FormCardProps {
    title: string
    handleSubmit?: (ev: FormEvent<HTMLFormElement>) => void,
    children: ReactNode
}

export function FormCard({title, handleSubmit, children}: FormCardProps) {
    return (
        <div className="relative py-16 bg-gray-50">
            <div className="container relative m-auto px-6 md:px-12 xl:px-40">
                <div className="m-auto space-y-8 md:w-8/12 lg:w-6/12 xl:w-6/12 mt-10">
                    <div
                        className="rounded-md border border-gray-100 bg-white shadow-lg shadow-gray-600/30 backdrop-blur-2xl">
                        <div className="p-8 py-12 sm:p-16">
                            <form onSubmit={handleSubmit} className="relative gap-6 flex flex-col justify-center">
                                <h2 className="text-2xl font-extrabold mb-4">{title}</h2>
                                {children}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

// src/app/shared/components/form-card/form-card.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-form-card',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './form-card.component.html',
})
export class FormCardComponent {
  @Input() formTitle: string = '';
  @Input() error: string | null = '';
}

<div class="relative py-20 bg-gray-50">
  <div class="container relative m-auto px-6 md:px-12 xl:px-48">
    <div class="m-auto space-y-8 md:w-8/12 lg:w-6/12 xl:w-6/12 mt-10">
      <div class="rounded-md border border-gray-100 bg-white shadow-lg shadow-gray-600/30 backdrop-blur-2xl">
        <div class="p-8 py-12 sm:p-16">
          <h2 class="text-2xl font-extrabold mb-8">{{ formTitle }}</h2>
          @if (error) {
            <div
              class="duration-300 mb-8"
              [ngClass]="error ? 'flex p-3 items-center gap-4 bg-gray-100 border-l-4 border-red-500' : 'hidden'">
              {{ error }}
            </div>
          }
          <ng-content />
        </div>
      </div>
    </div>
  </div>
</div>
