// app/core/utils/Topbar.tsx
"use client";

import {useState} from "react";
import Link from "next/link";
import logo from "@/public/logo.png";
import Image from "next/image";
import {usePathname, useRouter} from "next/navigation";
import useStore from "@/app/core/hooks/useStore";
import {api} from "@/app/core/config/api";
import {User} from "@/app/core/models/User";

type Link = {
    name: string;
    path: string;
    isShown: boolean;
};

export default function Topbar() {
    const [isOpen, setIsOpen] = useState<boolean>(false);
    const pathname: string = usePathname();
    const router = useRouter();
    const user: User | null = useStore.use.user();
    const setUser = useStore.use.setUser();

    const logOut = async (e: any) => {
        e.preventDefault();
        router.push("/");
        setUser(null);
        await api.post("auth/logout");
    };

    const trimName = (name: string) => {
        if (name.length > 15) {
            return name.substring(0, 15) + "...";
        }
        return name;
    };

    const LINKS: Link[] = [
        {
            name: "Accueil",
            path: "/",
            isShown: true,
        },
        {
            name: "Solutions",
            path: "/solutions",
            isShown: true,
        },
        {
            name: "Se connecter",
            path: "/login",
            isShown: user === null,
        },
        {
            name: "S'inscrire",
            path: "/register",
            isShown: user === null,
        },
        {
            name: trimName(user?.name || ""),
            path: "/me",
            isShown: user !== null,
        },
    ];

    return (
        <header
            className={`fixed w-full text-gray-800 bg-white shadow-md px-10 py-4 z-10 flex items-center justify-between`}
        >
            <Link href={"/"} className={"inline-block"} aria-label="logo">
                <Image
                    src={logo}
                    alt={"Logo"}
                    className={"cursor-pointer w-24"}
                    priority={true}
                />
            </Link>
            <div className={`flex flex-col gap-2 lg:hidden ${isOpen && "active"}`} onClick={() => {
                setIsOpen(!isOpen);
            }}>
                <div className="h-[1px] w-6 bg-black transition-transform duration-300"></div>
                <div className="h-[1px] w-6 bg-black transition-transform duration-300"></div>
            </div>

            {/* Mobile navbar */}
            <div
                className={`absolute top-14 z-30 w-screen h-screen bg-white transition-transform shadow-xl duration-500 right-0 py-20 px-16 flex flex-col items-start gap-6 justify-start lg:hidden ${!isOpen && "-translate-y-[200%]"}`}>
                {LINKS.map(
                    (link, index) =>
                        link.isShown && (
                            <Link href={link.path} key={index}
                                  className={`transition-colors duration-300 flex items-center gap-1 ${pathname === link.path && "text-blue-800"}`}>
                                {link.name}
                            </Link>
                        )
                )}
                {user && <button onClick={logOut}>Déconnexion</button>}
            </div>

            {/* Desktop navbar */}
            <div className={"hidden lg:flex items-center gap-4"}>
                {LINKS.map(
                    (link, index) =>
                        link.isShown && (
                            <Link href={link.path} key={index}
                                  className={`transition-colors duration-300 flex items-center gap-1 ${pathname === link.path && "text-blue-800"}`}>
                                {link.name}
                            </Link>
                        )
                )}
                {user && <button onClick={logOut}>Déconnexion</button>}
            </div>
        </header>
    );
}

// src/app/shared/components/topbar/topbar.component.ts
import {Component,} from '@angular/core';
import {CommonModule, NgOptimizedImage} from '@angular/common';
import {Router, RouterModule} from '@angular/router';
import {select, Store} from '@ngrx/store';
import {Observable} from 'rxjs';
import {authActions} from "../../auth/data-access/auth.actions";
import {selectUser as selectAuthUser} from "../../auth/data-access/auth.reducers";
import {User} from "../../types/models-interfaces";
import {LinkInterface} from "./types/link.interface";
import {FormsModule} from "@angular/forms";
import {AppStoreInterface} from "../../types/app-store.interface";

@Component({
  selector: 'app-topbar',
  standalone: true,
  imports: [CommonModule, RouterModule, NgOptimizedImage, FormsModule],
  templateUrl: './topbar.component.html',
})
export class TopbarComponent {
  user$: Observable<User | null>
  isOpen: boolean = false

  constructor(private store: Store<AppStoreInterface>, private router: Router) {
    this.user$ = this.store.pipe(select(selectAuthUser));
  }

  commonLinks: LinkInterface[] = [
    {
      name: 'Accueil',
      path: '/',
    },
    {
      name: 'Solutions',
      path: '/solutions',
    },
  ];

  authLinks: LinkInterface[] = [
    {
      name: 'Se connecter',
      path: '/login',
    },
    {
      name: "S'inscrire",
      path: '/register',
    },
  ];

  unAuthenticatedUserLinks(): LinkInterface[] {
    return [
      ...this.commonLinks,
      ...this.authLinks
    ];
  }

  authenticatedUserLinks(username: string): LinkInterface[] {
    return [
      ...this.commonLinks,
      {
        name: this.trimName(username),
        path: '/profile',
      },
    ];
  }

  logOut(): void {
    return this.store.dispatch(authActions.logout());
  }

  private trimName(name: string): string {
    return name.length > 15 ? name.substring(0, 15) + '...' : name;
  }

  openNavbar(): void {
    this.isOpen = true
  }

  closeNavbar(): void {
    this.isOpen = false
  }

  isActive(path: string): boolean {
    return this.router.url === path;
  }
}

<header class="relative h-full">
  <nav [ngClass]="isOpen ? 'lg:static fixed top-0 bottom-0 right-0 left-0 bg-white/75 z-10' : ''">
    <ul
      class="navbar fixed w-full top-0 left-0 right-0 translate-y-0 lg:px-20 px-10 py-3 transition-transform duration-300 text-gray-800 bg-white shadow-sm z-20 flex items-center justify-between">
      <a routerLink="/" class="flex items-center gap-3 cursor-pointer" aria-label="logo" (click)="closeNavbar()">
        <img ngSrc="/assets/images/favicon.png" alt="logo" class="cursor-pointer w-8" width="64" height="68" priority />
        <h1 class="font-bold text-2xl">fikiri<span class="text-emerald-400 animate-ping">.</span></h1>
      </a>
      <button
        class="flex flex-col cursor-pointer gap-2 lg:hidden"
        [ngClass]="isOpen ? 'nav-open' : ''"
        (click)="isOpen ? closeNavbar() : openNavbar()">
        <div class="h-[1px] w-6 bg-current transition-transform duration-300"></div>
        <div class="h-[1px] w-6 bg-current transition-transform duration-300"></div>
      </button>
      <!-- Desktop navbar -->
      <div class="hidden lg:flex gap-5">
        @if (user$ | async; as user) {
          @for (link of commonLinks; track $index) {
            <a
              [routerLink]="link.path"
              class="hover:text-green-400 transition-colors duration-300"
              (click)="closeNavbar()"
              routerLinkActive="text-green-400"
              [routerLinkActiveOptions]="{ exact: true }">
              {{ link.name }}
            </a>
          }
          <a
            routerLink="/profile"
            class="hover:text-green-400 transition-colors duration-300"
            (click)="closeNavbar()"
            routerLinkActive="text-green-400"
            [routerLinkActiveOptions]="{ exact: true }">
            {{ trimName(user.name) }}
          </a>
          <button href="" class="hover:text-green-400 transition-colors duration-300" (click)="logOut()">
            Déconnexion
          </button>
        } @else {
          @for (link of unAuthenticatedUserLinks; track $index) {
            <a
              [routerLink]="link.path"
              class="hover:text-green-400 transition-colors duration-300"
              (click)="closeNavbar()"
              routerLinkActive="text-green-400"
              [routerLinkActiveOptions]="{ exact: true }">
              {{ link.name }}
            </a>
          }
        }
      </div>
    </ul>
    <!-- Mobile navbar -->
    <div
      class="lg:hidden fixed top-14 left-0 right-16 backdrop-blur-lg bottom-0 bg-white z-40 transition-transform duration-300"
      [ngClass]="isOpen ? 'translate-x-0' : '-translate-x-[200%]'">
      <div class="flex flex-col gap-5 p-20 py-40">
        @if (user$ | async; as user) {
          @for (link of commonLinks; track $index) {
            <a
              [routerLink]="link.path"
              class="hover:text-green-400 transition-colors duration-300"
              (click)="closeNavbar()"
              routerLinkActive="text-green-400"
              [routerLinkActiveOptions]="{ exact: true }">
              {{ link.name }}
            </a>
          }
          <a
            routerLink="/profile"
            class="hover:text-green-400 transition-colors duration-300"
            (click)="closeNavbar()"
            routerLinkActive="text-green-400"
            [routerLinkActiveOptions]="{ exact: true }">
            {{ trimName(user.name) }}
          </a>
          <button href="" class="hover:text-green-400 transition-colors duration-300" (click)="logOut()">
            Déconnexion
          </button>
        } @else {
          @for (link of unAuthenticatedUserLinks; track $index) {
            <a
              [routerLink]="link.path"
              class="hover:text-green-400 transition-colors duration-300"
              (click)="closeNavbar()"
              routerLinkActive="text-green-400"
              [routerLinkActiveOptions]="{ exact: true }">
              {{ link.name }}
            </a>
          }
        }
      </div>
    </div>
  </nav>
</header>
