// src/app/solutions/solutions-list/solutions.component.ts
import { Component } from '@angular/core';
import { Solution } from '../../shared/types/models-interfaces';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { SolutionCardComponent } from '../../shared/ui/solution-card/solution-card.component';
import { TopbarComponent } from '../../shared/ui/topbar/topbar.component';
import { FooterComponent } from '../../shared/ui/footer/footer.component';

@Component({
  selector: 'fk-solutions',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    SolutionCardComponent,
    TopbarComponent,
    FooterComponent,
  ],
  templateUrl: './solutions.component.html',
})
export class SolutionsComponent {
  solutions: Solution[] = [];
}

<div class="relative">
  <ui-topbar />
  <div
    class="p-8 pt-28 text-gray-600 border-x border-dashed lg:mx-auto lg:max-w-screen-lg"
  >
    <h3 class="text-2xl font-bold mb-5">
      Les solutions innovantes de la communauté
      <span class="text-indigo-700">{{ solutions.length }}</span>
    </h3>
    <p class="mb-10">
      Les solutions innovantes de la communauté sont des projets qui ont été mis
      en place par des organisations locales ou des individus pour résoudre les
      problèmes de la communauté.
    </p>
    <div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
      @for (solution of solutions; let i = $index; track i) {
      <fk-solution-card [solution]="solution" />
      }
    </div>
    <div class="flex mt-8 w-full justify-center items-center text-sm">
      <hr class="w-full border-gray-300" />
      <button
        type="button"
        class="bg-none border w-1/2 rounded-full py-2 px-8 text-gray-950 hover:bg-gray-300/40 duration-75 disabled:opacity-50 disabled:pointer-events-none disabled:cursor-not-allowed"
      >
        Voir plus
      </button>
      <hr class="w-full border-gray-300" />
    </div>
  </div>
  <ui-footer />
</div>

// app/solutions/page.tsx
import { Footer } from "@/app/shared/utils/Footer";
import Topbar from "@/app/shared/utils/Topbar";
import { SolutionCard } from "@/app/solutions/components/SolutionCard";
import { Solution } from "@/app/shared/models/Solution";
import { Skeleton } from "@/app/shared/utils/ui/skeleton";
import { getMany } from "@/app/shared/_requests";

export default async function Solutions() {
  const solutions = await getMany<Solution[]>("solutions/mapped");

  return (
    <div className={"relative"}>
      <Topbar />
      <div
        className={
          "p-8 pt-28 text-gray-600 border-x border-dashed lg:mx-auto lg:max-w-screen-lg"
        }
      >
        <h3 className={"text-2xl font-bold mb-5"}>
          Les solutions innovantes de la communauté{" "}
          <span className={"text-indigo-700"}>({solutions.length})</span>
        </h3>
        <p className={"mb-10"}>
          Les solutions innovantes de la communauté sont des projets qui ont été
          mis en place par des organisations locales ou des individus pour
          résoudre les problèmes de la communauté.
        </p>
        <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
          {!solutions &&
            Array.from({ length: 10 }, (_, i) => (
              <Skeleton key={i} className={"animate-pulse h-[250px]"} />
            ))}
          {solutions &&
            solutions.map((solution: Solution, index: number) => (
              <SolutionCard key={index} solution={solution} />
            ))}
        </div>
      </div>
      <Footer />
    </div>
  );
}
