// app/components/Hero.tsx
import Link from "next/link";
import {WEB_SOLUTIONS_SUBMIT} from "@/app/shared/config/urls";

export function Hero() {

    return (
        <div className="bg-hero bg-center bg-cover">
            <div className={"p-8 h-full pt-32 pb-28 flex flex-col items-center justify-center bg-indigo-800/60 text-gray-50 mx-auto"}>
                <div className={"flex flex-col justify-center items-start gap-6 mx-auto md:max-w-screen-lg"}>
                    <h2 className={`text-xl md:text-4xl text-gray-50 font-semibold mt-6 md:w-2/3`}>
                        Cartographie des solutions innovantes locales pour accélérer
                        l&apos;atteinte des ODD en RDC.
                    </h2>
                    <p className={"md:w-2/3 md:text-xl font-medium mb-3"}>
                        Fikiri est une plateforme web qui vise à cartographier les
                        solutions locales en République Démocratique du Congo pour
                        accélérer l&apos;atteinte des Objectifs de Développement Durable
                        (ODD).
                    </p>
                    <Link href={WEB_SOLUTIONS_SUBMIT}
                          className={"px-6 text-lg fade-in-3 py-2 inline-block mb-10 rounded-md bg-indigo-500 text-white font-semibold"}>
                        Postulez dès maintenant
                    </Link>
                </div>
            </div>
        </div>
    );
}

// src/app/home/components/hero/hero.component.ts
import {Component, OnInit} from '@angular/core';
import {RouterLink} from "@angular/router";
import {AsyncPipe, NgIf, NgOptimizedImage} from "@angular/common";
import {HeroStore} from "./data-access/hero.store";
import {Observable} from "rxjs";
import {HeroStoreInterfce} from "./types/hero-store.interfce";
import {TopbarComponent} from "../../../shared/components/topbar/topbar.component";

@Component({
  selector: 'app-hero',
  standalone: true,
  imports: [RouterLink, NgOptimizedImage, NgIf, AsyncPipe, TopbarComponent],
  providers: [HeroStore],
  templateUrl: './hero.component.html',
})
export class HeroComponent implements OnInit {
  vm$: Observable<HeroStoreInterfce>

  constructor(private store: HeroStore) {
    this.vm$ = this.store.vm$;
  }

  ngOnInit(): void {
    this.store.getTotals()
  }
}

<div class="bg-hero bg-center bg-cover text-white flex flex-col" *ngIf="vm$ | async as vm">
  <app-topbar/>
  <div
    class="px-8 md:px-16 py-48 lg:px-32 h-full w-full flex flex-col justify-center items-start bg-black bg-opacity-80 gap-6 text-2xl md:text-4xl">
   <div class="mx-auto max-w-screen-md">
     <h1 class="font-bold mt-20 mb-10">Atteindre les objectifs de développement durable
       <span class="inline-block after:block after:w-full after:h-2 after:-mt-2 after:bg-emerald-300">fikiri</span>
       <span class="text-emerald-300 animate-pulse">.</span>
     </h1>
     <p class="font-light">
       Une plateforme d'accompagnement d'idées et de solutions
     </p>
     <div class="flex gap-10 text-xl mt-10 font-semibold">
       <div class="flex flex-col gap-3 items-center">
         <h1 class="">Utilisateurs</h1>
         <p class="font-bondiMono">+ {{ vm.totals?.totalUsers }}</p>
       </div>
       <div class="flex flex-col gap-3 items-center">
         <h1 class="">Solutions</h1>
         <p class="font-bondiMono">+ {{ vm.totals?.totalSolutions }}</p>
       </div>
     </div>
   </div>
  </div>
</div>
