// app/(pages)/reset-password-request/page.tsx
"use client";

import {FormEvent} from "react";
import Link from "next/link";
import {FormCard} from "@/app/shared/utils/formCard";
import Topbar from "@/app/shared/utils/Topbar";
import {toast, Toaster} from "react-hot-toast";
import {useRouter} from "next/navigation";
import {Label} from "@/app/shared/utils/ui/label";
import {Input} from "@/app/shared/utils/ui/input";
import {Button} from "@/app/shared/utils/ui/button";
import {Loader2} from "lucide-react";
import {getInputError} from "@/app/shared/helpers/getInputError";
import {useMutate} from "@/app/shared/hooks/useMutate";
import {post} from "@/app/shared/_requests";

export default function Login() {
    const router = useRouter()

    const resetPasswordRequest = async function (e: FormEvent) {
        const formData = new FormData(e.target as HTMLFormElement)
        const payload = Object.fromEntries(formData)
        return await post('auth/reset-password-request', payload)
    }

    const onSuccess = function () {
        toast.success('Mot de passe envoyé par email')
        router.push('/reset-password')
    }

    const {isLoading, errors, mutate} = useMutate(resetPasswordRequest, onSuccess)

    return (
        <div className={'relative'}>
            <Topbar/>
            <FormCard title={"Réinitialisation"} handleSubmit={mutate}>

                <div className="mb-3 -mt-6">
                    <p className="text-sm">
                        Entrez votre adresse email pour recevoir un code à 6 chiffres par mail pour réinitialiser votre
                        mot de passe,
                        sur la page suivante, vous pourrez entrer le code reçu par mail et choisir un nouveau mot de
                        passe.
                    </p>
                </div>

                <Label htmlFor={'email'}>Email</Label>
                <Input name={'email'} placeholder={'Entrez votre email'} error={getInputError(errors, 'email')}/>
                <Button type={'submit'} disabled={isLoading} className={'mt-5'}>
                    {
                        isLoading ? (
                            <>
                                <Loader2 className="mr-2 h-4 w-4 animate-spin"/>
                                En cours ...
                            </>
                        ) : "Réinitialiser"
                    }
                </Button>
                <Link href={'/login'} className="text-gray-950 text-sm">
                    Vous avez un compte ? Connectez-vous.
                </Link>
            </FormCard>
            <Toaster/>
        </div>
    );
}

// src/app/auth/reset-password-request/reset-password-request.component.ts
import {Component} from '@angular/core';
import {FormCardComponent} from '../../shared/components/form-card/form-card.component';
import {ButtonComponent} from '../../shared/ui/button/button.component';
import {InputComponent} from '../../shared/ui/input/input.component';
import {RouterLink} from '@angular/router';
import {AsyncPipe, NgIf, NgOptimizedImage} from '@angular/common';
import {ButtonOutlineComponent} from '../../shared/ui/button-outline/button-outline.component';
import {FormBuilder, FormGroup, ReactiveFormsModule, Validators,} from '@angular/forms';
import {environment} from "../../../environments/environment";
import {Observable} from "rxjs";
import {ResetPasswordRequestStore} from "./data-access/reset-password-request.store";
import {ResetPasswordRequestStoreInterface} from "./types/reset-password-request-store.interface";

@Component({
  selector: 'app-reset-password-request',
  standalone: true,
  imports: [
    FormCardComponent,
    ButtonComponent,
    InputComponent,
    RouterLink,
    NgOptimizedImage,
    ButtonOutlineComponent,
    ReactiveFormsModule,
    AsyncPipe,
    NgIf,
  ],
  providers: [ResetPasswordRequestStore],
  templateUrl: './reset-password-request.component.html'
})
export class ResetPasswordRequestComponent {
  form: FormGroup;
  apiUrl: string = environment.apiUrl
  vm$: Observable<ResetPasswordRequestStoreInterface>

  constructor(private store: ResetPasswordRequestStore, private formBuilder: FormBuilder) {
    this.vm$ = this.store.vm$
    this.form = this.formBuilder.group({
      email: ['', Validators.required],
    });
  }

  onSubmit(): void {
    this.store.resetPassword(this.form.value);
  }

  loginWithGoogle(): void {
    return window.location.replace(`${this.apiUrl}auth/google/redirect`);
  }
}

<app-form-card formTitle="Réinitialisation" *ngIf="vm$ | async as state" [error]="state.error">
  <div class="mb-6 -mt-4">
    <p class="text-sm">
      Entrez votre adresse email pour recevoir un code à 6 chiffres par mail
      pour réinitialiser votre mot de passe, sur la page suivante, vous
      pourrez entrer le code reçu par mail et choisir un nouveau mot de
      passe.
    </p>
  </div>
  <form [formGroup]="form" (ngSubmit)="onSubmit()" class="gap-8 flex flex-col justify-center">
    <app-input type="email" label="Email" placeholder="Entrez votre email" name="email"
              [validationErrors]="state.validationErrors"/>
    <app-button type="submit" [loading]="state.isLoading" [disabled]="form.invalid">
      Vérifier mon email
    </app-button>
    <hr class="border-gray-300 w-full"/>
    <app-button-outline (click)="loginWithGoogle()">
      <img ngSrc="../../../assets/images/google.svg" alt="google" class="mr-2 h-4 w-4" width="10" height="10"/>
      <span class="text-gray-950 text-sm">Se connecter avec Google</span>
    </app-button-outline>
    <a routerLink="/login" class="text-gray-950 text-sm">
      Vous avez un compte ? Connectez-vous
    </a>
  </form>
</app-form-card>
