// app/shared/utils/ui/input.tsx
import * as React from "react"

import {cn} from "@/lib/utils"

export interface InputProps
    extends React.InputHTMLAttributes<HTMLInputElement> {
    error?: string
}

const Input = React.forwardRef<HTMLInputElement, InputProps>(
    ({className, type, error, ...props}, ref) => {
        return (
            <div className="flex flex-col gap-1">
                <input
                    type={type}
                    className={cn(
                        "flex h-9 w-full rounded-md border border-input bg-background px-3 py-5 text-sm shadow-sm transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50",
                        className
                    )}
                    ref={ref}
                    {...props}
                />
                {
                    error && (
                        <p className="text-red-700 text-sm">
                            {error}
                        </p>
                    )
                }
            </div>
        )
    }
)
Input.displayName = "Input"

export {Input}

// src/app/shared/ui/input/input.component.ts
import {Component, inject, Input} from "@angular/core";
import {ControlContainer, ReactiveFormsModule} from "@angular/forms";

@Component({
  selector: 'ui-input',
  standalone: true,
  viewProviders: [
    {
      provide: ControlContainer,
      useFactory: () => inject(ControlContainer, {skipSelf: true})
    }
  ],
  imports: [
    ReactiveFormsModule
  ],
  templateUrl: './input.component.html',
})
export class InputComponent {
  @Input() name: string = ''
  @Input() label: string = ''
  @Input() type: 'email' | 'password' | 'text' | 'number' = 'text'
  @Input() placeholder: string = ''
}

<div class="flex flex-col gap-3">
  <label
    [htmlFor]="name"
    class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
    >{{ label }}</label
  >
  <input
    [type]="type"
    [id]="name"
    autocomplete="on"
    class="flex h-9 w-full rounded-md border border-input bg-background px-3 py-5 text-sm shadow-sm transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50"
    [placeholder]="placeholder"
    [name]="name"
    [formControlName]="name" />
  @if (validationErrors.length > 0) {
    <p class="text-sm text-red-500">{{ getError(name) }}</p>
  }
</div>
